spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/diplomablog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto: validate

spring.jpa.show-sql: true

spring.flyway.enabled: true

spring.servlet.multipart:
  max-file-size: 200KB
  max-request-size: 200KB

spring.mail:
  host: smtp.gmail.com
  username: defdevblog@gmail.com
  password: test123test
  port: 587
  smtp.auth: true
  protocol: smtp

mail.debug: true

server.port: ${PORT:8080}

captcha:
  updateTime: 1
  image:
    width: 100
    height: 35

jwt:
  token:
    secret: secretkey
    expired: 86400000

