spring.datasource.url: jdbc:mysql://localhost:3306/diplomablog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL8InnoDBDialect
spring.jpa.hibernate.ddl-auto: validate

spring.jpa.show-sql: true

spring.flyway.enabled: true

java.runtime.version: 11
