spring.datasource.url: jdbc:mysql://localhost:3306/diplomablog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: create
MULTIUSER_MODE: YES
POST_PREMODERATION: YES
STATISTICS_IS_PUBLIC: YES