INSERT INTO `posts` (`is_active`, `moderation_status`, `moderator_id`, `puser_id`, `ptime` , `title` , `ptext`, `view_count`)
    VALUES
        (1, 'ACCEPTED', 1, 1, NOW() - INTERVAL 8 DAY, 'Третий пост', 'Текст третего поста', 10),
        (1, 'ACCEPTED', 1, 1, NOW() - INTERVAL 7 DAY , 'Четвертый пост', 'Текст четвертого поста', 5),
        (1, 'ACCEPTED', 1, 1, NOW() - INTERVAL 6 DAY , 'Пятый пост', 'Текст пятого поста', 11),
        (1, 'ACCEPTED', 1, 2, NOW() - INTERVAL 5 DAY, 'Шестой пост', 'Текст шестого поста', 5),
        (1, 'ACCEPTED', 1, 1, NOW() - INTERVAL 4 DAY, 'Седьмой пост', 'Текст седьмого поста', 2),
        (1, 'ACCEPTED', 1, 1, NOW() - INTERVAL 3 DAY, 'Восьмой пост', 'Текст восьмого поста', 1),
        (1, 'ACCEPTED', 1, 1, NOW() - INTERVAL 2 DAY, 'Девятый пост', 'Текст девятого поста', 1),
        (1, 'NEW', 1, 1, NOW() - INTERVAL 1 DAY, 'Десятый пост', 'Текст десятого поста', 1),
        (1, 'ACCEPTED', 1, 1, NOW() - INTERVAL 2 HOUR, 'Одиннадцатый пост', 'Текст одиннадцатого поста', 1),
        (1, 'ACCEPTED', 1, 1, NOW(), 'Двенадцатый пост', 'Текст двенадцатого поста', 1);

insert into posts (is_active, moderation_status, moderator_id, puser_id, ptime, title, ptext, view_count)
    VALUES (1, 'ACCEPTED', '1', '1', '2019-10-22 06:56:02', 'Zapped!', 'enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris', 19),
        (1, 'ACCEPTED', '1', '1', '2019-12-18 11:32:25', 'Deep Crimson (Profundo carmesí)', 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 77),
        (1, 'ACCEPTED', '1', '1', '2020-06-12 01:01:55', 'Madhouse', 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 52),
        (1, 'ACCEPTED', '1', '1', '2020-08-22 13:33:48', 'Some Days Are Better Than Others', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur', 63),
        (1, 'ACCEPTED', '1', '1', '2020-01-08 22:11:04', 'Callejón de los milagros, El', 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque', 93),
        (1, 'ACCEPTED', '1', '1', '2019-10-26 22:41:07', 'Adulthood', 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 14),
        (1, 'ACCEPTED', '1', '1', '2019-12-24 12:38:01', 'Heart of Glass (Herz aus Glas)', 'blandit mi in porttitor pede justo eu massa donec dapibus', 94),
        (1, 'ACCEPTED', '1', '1', '2020-02-16 13:18:01', 'Marjoe', 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 88),
        (1, 'ACCEPTED', '1', '1', '2020-02-18 21:15:28', 'Backwood Philosopher (Havukka-ahon ajattelija)', 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis', 63),
        (1, 'ACCEPTED', '1', '1', '2020-02-22 05:38:14', 'Ass Backwards', 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio', 39),
        (0, 'ACCEPTED', '1', '1', '2020-03-26 17:27:09', 'Education for Death', 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat', 22),
        (1, 'ACCEPTED', '1', '1', '2020-09-10 10:15:08', 'Devil''s Own, The', 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi', 50),
        (1, 'ACCEPTED', '1', '1', '2020-05-29 13:49:30', 'Endless Love', 'a libero nam dui proin leo odio porttitor id consequat in consequat', 81),
        (1, 'ACCEPTED', '1', '1', '2020-02-09 19:52:46', 'Love Is Colder Than Death (Liebe ist kälter als der Tod)', 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem', 20),
        (1, 'ACCEPTED', '1', '1', '2020-08-17 00:24:33', 'Convent, The', 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 68),
        (1, 'ACCEPTED', '1', '1', '2020-06-10 08:37:14', 'In the Fog (V tumane)', 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 81),
        (1, 'ACCEPTED', '1', '1', '2020-07-21 03:16:12', 'Too Late Blues', 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui', 63),
        (1, 'ACCEPTED', '1', '1', '2020-05-10 10:37:17', 'Fall of the House of Usher, The (Zánik domu Usheru)', 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla', 58),
        (1, 'ACCEPTED', '1', '1', '2020-02-11 19:55:41', 'Tuxedo, The', 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor', 16),
        (1, 'ACCEPTED', '1', '1', '2020-08-24 11:09:45', 'Hector and the Search for Happiness', 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 58),
        (1, 'ACCEPTED', '1', '1', '2019-10-20 22:19:54', 'Obsession', 'eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 13),
        (1, 'ACCEPTED', '1', '1', '2020-03-28 03:32:43', 'Tall Man, The', 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 30),
        (1, 'ACCEPTED', '1', '1', '2020-03-30 00:03:24', 'Triplets of Belleville, The (Les triplettes de Belleville)', 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', 52),
        (1, 'ACCEPTED', '1', '1', '2020-01-20 20:57:42', 'Wordplay', 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla', 13),
        (1, 'ACCEPTED', '1', '1', '2020-07-26 01:51:53', 'Over the Hedge', 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 44),
        (1, 'ACCEPTED', '1', '1', '2020-01-19 00:24:53', 'Black Field', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer', 38),
        (1, 'ACCEPTED', '1', '1', '2020-09-15 14:44:12', 'Pictures of the Old World (Obrazy starého sveta)', 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper', 33),
        (1, 'ACCEPTED', '1', '1', '2020-09-03 12:34:59', 'Spring, Summer, Fall, Winter... and Spring (Bom yeoreum gaeul gyeoul geurigo bom)', 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis', 44),
        (1, 'ACCEPTED', '1', '1', '2019-12-15 06:10:44', 'Little Giant, The', 'turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris', 97),
        (1, 'ACCEPTED', '1', '1', '2020-05-03 05:46:43', 'Begotten', 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', 77);